<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC7-D-452SM71" name="Functional Tests" tests="5" failures="1" timestamp="11 Aug 2016 06:43:01 GMT" time="0.111" errors="0">
  <testcase name="bFunctionalTest" time="0.021" classname="testnglearning.NewTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at testnglearning.NewTest.bFunctionalTest(NewTest.java:40)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- bFunctionalTest -->
  <testcase name="dFunctionalTest" time="0.02" classname="testnglearning.NewTest"/>
  <testcase name="wFunctionalTest" time="0.021" classname="testnglearning.SecondTest"/>
  <testcase name="yFunctionalTest" time="0.02" classname="testnglearning.SecondTest"/>
  <testcase name="zFunctionalTest" time="0.02" classname="testnglearning.SecondTest"/>
</testsuite> <!-- Functional Tests -->
